variables:
  VERSION_ID: '1.0.$CI_PIPELINE_ID'

stages:
  - test
  - build
  
test-app:
  stage: test
  image: node:lts-alpine
  script:
    - npm install

win-build:
  stage: build
  image: electronuserland/builder:wine
  artifacts:
    expire_in: 1 days
    paths:
      - $CI_PROJECT_DIR/dist/*.*
      - mkdir .public
      - cp -r packages/app/desktop/build/installers/* .public
      - mv .public public
  script:
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - npm install && npm run build




